[phases.setup]
nixPkgs = ["python312", "python312Packages.pip", "python312Packages.virtualenv", "gcc", "postgresql"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  "/opt/venv/bin/pip install --upgrade pip",
  "/opt/venv/bin/pip install -r requirements.txt"
]

[phases.build]
cmds = ["/opt/venv/bin/python manage.py collectstatic --noinput"]

[start]
cmd = "/opt/venv/bin/gunicorn redneck.wsgi --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
