# Generated by Django 4.2.29 on 2026-03-20 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('product_type', models.CharField(choices=[('mutual_fund', 'Mutual Fund'), ('etf', 'ETF Portfolio'), ('retirement', 'Retirement Account (IRA/401k)'), ('annuity', 'Fixed Annuity'), ('bonds', 'Bond Portfolio'), ('stocks', 'Equity Portfolio'), ('real_estate', 'Real Estate Investment'), ('managed', 'Managed Portfolio')], max_length=30)),
                ('tagline', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('risk_level', models.CharField(choices=[('conservative', 'Conservative'), ('moderate', 'Moderate'), ('aggressive', 'Aggressive Growth')], max_length=20)),
                ('min_investment', models.DecimalField(decimal_places=2, default=1000, max_digits=12)),
                ('expected_return_low', models.DecimalField(decimal_places=2, help_text='Annual % return (low estimate)', max_digits=5)),
                ('expected_return_high', models.DecimalField(decimal_places=2, help_text='Annual % return (high estimate)', max_digits=5)),
                ('features', models.TextField(help_text='One feature per line')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('investment_goal', models.CharField(choices=[('retirement', 'Retirement Planning'), ('wealth', 'Wealth Building'), ('income', 'Passive Income'), ('college', 'College Funding'), ('estate', 'Estate Planning'), ('other', 'Other')], max_length=20)),
                ('time_horizon', models.CharField(choices=[('short', 'Short-term (1–3 years)'), ('medium', 'Medium-term (3–10 years)'), ('long', 'Long-term (10+ years)')], max_length=10)),
                ('initial_investment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('risk_tolerance', models.CharField(choices=[('conservative', 'Conservative'), ('moderate', 'Moderate'), ('aggressive', 'Aggressive Growth')], max_length=20)),
                ('additional_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_contacted', models.BooleanField(default=False)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investments.investmentproduct')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
